# initials.py
import time
import os
os.system("cls")
print("The code will be executed in |5| seconds")
time.sleep(1)
os.system("cls")
print("The code will be executed in |4| seconds")
time.sleep(1)
os.system("cls")
print("The code will be executed in |3| seconds")
time.sleep(1)
os.system("cls")
print("The code will be executed in |2| seconds")
time.sleep(1)
os.system("cls")
print("The code will be executed in |1| seconds")
time.sleep(1)
os.system("cls")
print("                      ___________    _____________    ________")
time.sleep(0.5)
print("        /\           |JJJJJJJJJJJ|  |TTTTTTTTTTTTT|  |PPPPPPPP\\")
time.sleep(0.5)
print("       /AA\           ‾‾‾‾|J|‾‾‾‾    ‾‾‾‾‾|T|‾‾‾‾‾   |P|‾‾‾‾‾\P|")
time.sleep(0.5)
print("      /A/\A\              |J|             |T|        |P|     |P|")
time.sleep(0.5)
print("     /A/  \A\             |J|             |T|        |P|_____/P|")
time.sleep(0.5)
print("    /A/____\A\            |J|             |T|        |PPPPPPPP/")
time.sleep(0.5)
print("   /AAAAAAAAAA\     _     |J|             |T|        |P|‾‾‾‾‾‾")
time.sleep(0.5)
print("  /A/‾‾‾‾‾‾‾‾\A\   |J|    |J|             |T|        |P|")
time.sleep(0.5)
print(" /A/          \A\  |J|____|J|             |T|        |P|")
time.sleep(0.5)
print("/A/            \A\  \JJJJJJ/              |T|        |P|")
time.sleep(0.5)
print("‾‾              ‾‾   ‾‾‾‾‾‾                ‾          ‾")
time.sleep(0.5)
print("the code has been executed")
input("press |Enter| to end")
os.system("cls")
exit
